---
# tasks file for roles/psql-database
- name: Create user 
  become: true
  become_user: postgres
  postgresql_user:
    user: "{{ item.username }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role_attr_flags }}" # CREATEROLE, NOCREATEROLE, CREATEDB, NOCREATEDB, SUPERUSER, NOSUPERUSER, LOGIN, NOLOGIN ...
    state: present
  with_items:
    - "{{ list_user }}"  

- name: Remove user 
  become: true
  become_user: postgres
  postgresql_user:
    user: "{{ item }}"
    state: absent
  with_items:
    - "{{ list_user_deleted }}"    

- name: Create the database 
  become: true
  become_user: postgres
  postgresql_db: 
    name: "{{ item }}"
    template: 'template0'
    state: present
  with_items:
    - "{{ list_database }}"     

- name: Remove the database 
  become: true
  become_user: postgres
  postgresql_db: 
    name: "{{ item }}"
    state: absent 
  with_items:
    - "{{ list_database_remove }}"

- name: Grant user has access to database
  become: true
  become_user: postgres
  postgresql_privs:
    database: "{{ item.db_name }}"
    privs: "{{ item.privs_list }}"
    roles: "{{ item.role_name }}"
    obj: "no"
  with_items:
    - "{{ list_privilege }}" 